FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# data/catalog.json must be present (generated by scraper.py locally)
RUN test -f data/catalog.json || (echo "ERROR: data/catalog.json not found. Run scraper.py first." && exit 1)

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
